version: "3.4"

volumes:
  l2_data:
  node:

services:
  l2:
    image: us-docker.pkg.dev/oplabs-tools-artifacts/images/op-geth:0402d543c3d0cff3a3d344c0f4f83809edb44f10
    ports:
      # l2 http rpc
      - "8545:8545"
      # l2 ws rpc
      - "8546:8546"
      # l2 authrpc
      - "8551:8551"
      # metrics
      - "6060:6060"
      # discovery.port
      - "30303:30303"

    volumes:
      - "l2_data:/db"
      - "./genesis.json:/genesis.json"
      - "./jwt.txt:/jwt.txt"
      - "./l2_entrypoint.sh:/l2_entrypoint.sh"
    entrypoint: # pass the L2 specific flags by overriding the entry-point and adding extra arguments
      - "/bin/sh"
      - "/l2_entrypoint.sh"
    env_file:
      - ./l2.env

  op-node:
    depends_on:
      - l2
    image: public.ecr.aws/altlayer/optimism-node:v1.7.0-da
    entrypoint: # pass the L2 specific flags by overriding the entry-point and adding extra arguments
      - "/bin/sh"
      - "/node_entrypoint.sh"
    ports:
      # op-node rpc
      - "9545:9545"
      # p2p tcp/udp
      - "9222:9222"
      # metrics
      - "7300:7300"
      # pprof
      # - "6060:6060"
      # conductor.rpc 
      - "8547:8547"
    volumes:
      - "node:/data/node"
      - "./jwt.txt:/jwt.txt"
      - "./rollup.json:/rollup.json"
      - "./node_entrypoint.sh:/node_entrypoint.sh"
    env_file:
      - ./node.env
