version: "3.8"

volumes:
  geth:
  node:

services:
  geth:
    image: us-docker.pkg.dev/oplabs-tools-artifacts/images/op-geth:v1.101311.0
    ports:
      # geth http rpc
      - "8545:8545"
      # geth ws rpc
      - "8546:8546"
      # geth eignine authrpc
      - "8551:8551"
      # geth metrics
      - "6060:6060"
      # geth p2p port
      - "30303:30303"

    volumes:
      - "geth_data:/data"
      - "./jwt.txt:/jwt.txt"
      - "./geth_entrypoint.sh:/geth_entrypoint.sh"
    entrypoint:
      - "/bin/sh"
      - "-c"
      - "/geth_entrypoint.sh"
    env_file:
      - ./geth.env

  op-node:
    depends_on:
      - geth
    image: public.ecr.aws/altlayer/optimism-node:v1.7.3
    entrypoint: 
      - "/bin/sh"
      - "-c"
      - "/node_entrypoint.sh"
    ports:
      # node rpc
      - "9545:9545"
      # node p2p 
      - "9003:9003"
      # node metrics
      - "7300:7300"
    volumes:
      - "node:/data"
      - "./jwt.txt:/jwt.txt"
      - "./node_entrypoint.sh:/node_entrypoint.sh"
    env_file:
      - ./node.env
